name: talkbridge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  avatar_glow: ^2.0.2
  country_flags: ^2.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.8.3
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  record: ^5.0.1
  speech_to_text: ^6.5.0
  translator_plus: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  mocktail: ^1.0.0

flutter_native_splash:
  background_image: assets/splash.png

flutter_icons:
  image_path: assets/logo.png
  android: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/