name: talkbridge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  avatar_glow: ^2.0.2
  country_flags: ^2.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_speech: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  record: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4


flutter:
  uses-material-design: true

  assets:
    - assets/talkbridge_service_account.json