name: talkbridge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  avatar_glow: ^2.0.2
  country_flags: ^2.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
 
  flutter_tts: ^3.8.3
  google_speech: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.1
  record: ^5.0.1
  translator_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0

flutter_native_splash:
  background_image: assets/splash.png

flutter_icons:
  image_path: assets/logo.png
  android: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/